### ISSUE TITLE
Interaction with dehydration mod | 1.19.2 fabric

### ISSUE THREAD

**Issue by Surpos0** [Jasel-Umena/Apocalypse-Origins#1]
When i picked hexblade as a origins i can't drink, but at the same time my dehydration bar is going down, and eventually i die.
I think that drinking water from glass bottle would be fine cuz he is made from wood.

dehydration - 1.3.1
Apocalypse - 0.3.66

**Comment by Jasel-Umena** [comment]
Hi, does this mod have alternative ways of drinking water (right clicking a water block, using canteens, etc) or is it just from water bottles?

**Comment by Surpos0** [comment]
In early game bottles are only way of surviving

**Comment by Jasel-Umena** [comment]
I'll look into it, but annoyingly water bottles are considered potions. Are you positive you can't just drink water from the source?

**Comment by Jasel-Umena** [comment]
Okay, it says here you can drink water from the source. You don't need bottles. [https://globoxwiki.com/mods/dehydration/](url)

**Comment by Surpos0** [comment]
Thanks. I was starting to worry that I would have to choose between one of these mods.
