### ISSUE TITLE
This is more of a in-game issue but Most sigils, v2 and up don’t work at all.

### ISSUE THREAD

**Issue by Lockl00p** [Jasel-Umena/Apocalypse-Origins#4]
I clicked secondary, it did nothing, doesn’t even pop the resource bar up.

**Comment by Lockl00p** [comment]
I’ve used 1.18.2 and 1.19.2 to test this.

**Comment by Jasel-Umena** [comment]
You kind of need to be the appropriate tier to use sigils. You will not be able to use sigils of impact 2 or above as impact 1.
