### ISSUE TITLE
Null error message

### ISSUE THREAD

**Issue by Chamelllemon** [Jasel-Umena/Apocalypse-Origins#6]
I made a modpack for myself and after I added this mod it started to show me this message:
The game crashed whilst initializing game
Error: java.lang.ExceptionInInitializerError: null

Whole error message:
[crash-2023-10-17_15.57.18-client.txt](https://github.com/Jasel-Umena/Apocalypse-Origins/files/12929771/crash-2023-10-17_15.57.18-client.txt)

Without this mod it works

**Comment by Jasel-Umena** [comment]
That would have to do with the fact that this is a Fabric mod. I recommend reading the "I have a problem" in the downloads page for a workaround.
